# Generated by Django 2.2.5 on 2019-12-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edit_online', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.IntegerField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=40)),
                ('creater_id', models.IntegerField()),
                ('type', models.CharField(max_length=10)),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'Project',
            },
        ),
    ]
