# Generated by Django 2.1.8 on 2019-12-19 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edit_online', '0003_auto_20191216_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
