# Generated by Django 2.2.5 on 2019-12-26 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edit_online', '0004_auto_20191219_1331'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='authorize',
            unique_together={('project_id', 'user_id')},
        ),
        migrations.AlterModelTable(
            name='authorize',
            table='auth_pro',
        ),
    ]
