# Generated by Django 2.2.5 on 2019-12-26 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edit_online', '0005_auto_20191227_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=40),
        ),
    ]
